// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/grpc-server/proto/arenaexample/parser.proto

package arenaexamplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseRequest) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Field               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Used          uint32                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Remaining     uint32                 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescGZIP(), []int{2}
}

func (x *ParseResponse) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ParseResponse) GetUsed() uint32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *ParseResponse) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int64                `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescGZIP(), []int{3}
}

func (x *SumRequest) GetNumbers() []int64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int64                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	ParsedNumbers []*Field               `protobuf:"bytes,2,rep,name=parsed_numbers,json=parsedNumbers,proto3" json:"parsed_numbers,omitempty"`
	Used          uint32                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Remaining     uint32                 `protobuf:"varint,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescGZIP(), []int{4}
}

func (x *SumResponse) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SumResponse) GetParsedNumbers() []*Field {
	if x != nil {
		return x.ParsedNumbers
	}
	return nil
}

func (x *SumResponse) GetUsed() uint32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *SumResponse) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

var File_examples_grpc_server_proto_arenaexample_parser_proto protoreflect.FileDescriptor

const file_examples_grpc_server_proto_arenaexample_parser_proto_rawDesc = "" +
	"\n" +
	"4examples/grpc-server/proto/arenaexample/parser.proto\x12\x0farenaexample.v1\"/\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\">\n" +
	"\fParseRequest\x12.\n" +
	"\x06fields\x18\x01 \x03(\v2\x16.arenaexample.v1.FieldR\x06fields\"q\n" +
	"\rParseResponse\x12.\n" +
	"\x06fields\x18\x01 \x03(\v2\x16.arenaexample.v1.FieldR\x06fields\x12\x12\n" +
	"\x04used\x18\x02 \x01(\rR\x04used\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\rR\tremaining\"&\n" +
	"\n" +
	"SumRequest\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x03R\anumbers\"\x90\x01\n" +
	"\vSumResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x03R\x03sum\x12=\n" +
	"\x0eparsed_numbers\x18\x02 \x03(\v2\x16.arenaexample.v1.FieldR\rparsedNumbers\x12\x12\n" +
	"\x04used\x18\x03 \x01(\rR\x04used\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\rR\tremaining2\x99\x01\n" +
	"\rParserService\x12F\n" +
	"\x05Parse\x12\x1d.arenaexample.v1.ParseRequest\x1a\x1e.arenaexample.v1.ParseResponse\x12@\n" +
	"\x03Sum\x12\x1b.arenaexample.v1.SumRequest\x1a\x1c.arenaexample.v1.SumResponseB`Z^github.com/Protocol-Lattice/memoryArena/examples/grpc-server/proto/arenaexample;arenaexamplepbb\x06proto3"

var (
	file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescOnce sync.Once
	file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescData []byte
)

func file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescGZIP() []byte {
	file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescOnce.Do(func() {
		file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_grpc_server_proto_arenaexample_parser_proto_rawDesc), len(file_examples_grpc_server_proto_arenaexample_parser_proto_rawDesc)))
	})
	return file_examples_grpc_server_proto_arenaexample_parser_proto_rawDescData
}

var file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_grpc_server_proto_arenaexample_parser_proto_goTypes = []any{
	(*Field)(nil),         // 0: arenaexample.v1.Field
	(*ParseRequest)(nil),  // 1: arenaexample.v1.ParseRequest
	(*ParseResponse)(nil), // 2: arenaexample.v1.ParseResponse
	(*SumRequest)(nil),    // 3: arenaexample.v1.SumRequest
	(*SumResponse)(nil),   // 4: arenaexample.v1.SumResponse
}
var file_examples_grpc_server_proto_arenaexample_parser_proto_depIdxs = []int32{
	0, // 0: arenaexample.v1.ParseRequest.fields:type_name -> arenaexample.v1.Field
	0, // 1: arenaexample.v1.ParseResponse.fields:type_name -> arenaexample.v1.Field
	0, // 2: arenaexample.v1.SumResponse.parsed_numbers:type_name -> arenaexample.v1.Field
	1, // 3: arenaexample.v1.ParserService.Parse:input_type -> arenaexample.v1.ParseRequest
	3, // 4: arenaexample.v1.ParserService.Sum:input_type -> arenaexample.v1.SumRequest
	2, // 5: arenaexample.v1.ParserService.Parse:output_type -> arenaexample.v1.ParseResponse
	4, // 6: arenaexample.v1.ParserService.Sum:output_type -> arenaexample.v1.SumResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_examples_grpc_server_proto_arenaexample_parser_proto_init() }
func file_examples_grpc_server_proto_arenaexample_parser_proto_init() {
	if File_examples_grpc_server_proto_arenaexample_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_grpc_server_proto_arenaexample_parser_proto_rawDesc), len(file_examples_grpc_server_proto_arenaexample_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_grpc_server_proto_arenaexample_parser_proto_goTypes,
		DependencyIndexes: file_examples_grpc_server_proto_arenaexample_parser_proto_depIdxs,
		MessageInfos:      file_examples_grpc_server_proto_arenaexample_parser_proto_msgTypes,
	}.Build()
	File_examples_grpc_server_proto_arenaexample_parser_proto = out.File
	file_examples_grpc_server_proto_arenaexample_parser_proto_goTypes = nil
	file_examples_grpc_server_proto_arenaexample_parser_proto_depIdxs = nil
}
